# wasm-tools compose -c config.yml -o composed.wasm middleware/target/wasm32-wasi/release/middleware.wasm

search-paths:
  - dist

instantiations:
  $input:
    arguments:
      calculator-calculate: calculator