# wasm-tools compose -c config.yml -o composed.wasm middleware/target/wasm32-wasi/release/middleware.wasm

search-paths:
  - target/wasm32-wasi/release

instantiations:
  $input:
    arguments:
      docs:calculator/calculate: calculator