spin_manifest_version = "1"
authors = ["thangchung <thangchung@ymail.com>"]
description = ""
name = "spin-app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-app"
source = "spin_app_command.wasm"
allowed_http_hosts = []

[component.trigger]
route = "/..."

[component.build]
command = "./build.sh"