apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kitchen-statestore-outbox
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "false"
    - name: outboxPublishPubsub # Required
      value: "kitchenpubsub"
    - name: outboxPublishTopic # Required
      value: "kitchenorderplaced"
