apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista-api
  template:
    metadata:
      labels:
        app: barista-api
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: barista-api
          image: ghcr.io/thangchung/dapr-labs/barista-api-spin:1.0.0
          command: ["/"]
          ports:
          - containerPort: 3000
          env:
          - name: RUST_BACKTRACE
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: barista-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 3000
  selector:
    app: barista-api
