package docs:calculator@0.1.0

interface calculate {
    enum op {
        add,
    }
    eval-expression: func(op: op, x: s32, y: s32) -> s32
}

interface add {
  add: func(a: s32, b: s32) -> s32 
}

world adder {
    export add
}

world calculator {
    export calculate
    import add
}

world app {
    import calculate
}
