version: "3.7"

services:
  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
    networks:
      - coffeeshop-network

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - coffeeshop-network

  # zipkin:
  #   image: openzipkin/zipkin:latest
  #   container_name: zipkin
  #   ports:
  #     - "9411:9411"
  #   networks:
  #     - coffeeshop-network

networks:
  coffeeshop-network: