spin_manifest_version = "1"
authors = ["thangchung <thangchung@ymail.com>"]
description = ""
name = "notification-api"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "notification-api"
source = "target/notification-api.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
